
## MZ B cell in mouse and man.
<hr>

Establishment and numbers comparison

Location

Repertoire

Memory generation

low frequency of IgM memory B cells correlates with increased susceptibility to peumonia in CVID patients
Suggesting that reduced serum levels of all immunoglobulin isotypes ability to produce antipolysaccharide IgM may act as a protective marker in CVID patients.

---

MZ B cell deficiency is considered to be a primary cause of increased frequency and severity of infections by pneumococcus and other encapsulated bacteria.

these diseases are 20–100 times more frequent in individuals with asplenia, splenectomy, and SCD

but also because of the increasing antibiotic resistance (20–50%).


A frequently used vaccine contains a mixture of capsular polysaccharides from the 23 most com- mon pneumococcal serotypes. This vaccine is not effective in any of the groups at risk for the infection (12), probably because, as we have shown, they lack IgM memory B cells, which are the cell type specialized for the response to poly- saccharides (9). This lack explains also why the polysaccharide vaccine does not induce memory and revaccination leads to a similar or even reduced serological response compared to primary vaccination

???

### It is hard to study MZ B cells in humans because hard to identify them in blood. Because they are spatially restricted to lymphoid locations.

Therefore our goal is to study them in mice first and translate the findings in humans (hopefully) later in more careful approaches.

---





